version: '3.9'

services:
  snapshot-dequeuer:
    image: proto-snapshot-dequeuer
    volumes:
      - ./shared_volume:/keys
    environment:
      - PROTOCOL_STATE_CONTRACT=$PROTOCOL_STATE_CONTRACT
      - PROST_RPC_URL=$PROST_RPC_URL
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - FULL_NODES=$FULL_NODES
      - PROST_CHAIN_ID=$PROST_CHAIN_ID

    command:
      bash -c  "sh dequeuer_autofill.sh && sh init_processes.sh"